name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t07&#45;00&#45;01
      id: t07-45-00-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;00&#45;01
        setup-command: make compile
        command: make -s test_00
        input: ''
        expected-output: '10S1002|Procedural Programming|2|D

          '
        comparison-method: exact
        timeout: 1
        max-score: 0
    - name: t07&#45;01&#45;01
      id: t07-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: ''
        expected-output: '12S22999|Wiro Sableng|2022|Information Systems

          '
        comparison-method: exact
        timeout: 1
        max-score: 30
    - name: t07&#45;02&#45;01
      id: t07-45-02-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;02&#45;01
        setup-command: make compile
        command: make -s test_02
        input: ''
        expected-output: |
          10S1002|Procedural Programming|2|D
          12S22999|Wiro Sableng|2022|Information Systems
          10S1002|12S22999|None|0.00
          10S1002|12S22999|AB|7.00
        comparison-method: exact
        timeout: 1
        max-score: 30
    - name: t07&#45;03&#45;01
      id: t07-45-03-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t07&#45;03&#45;01
        setup-command: make compile
        command: make -s test_03
        input: ''
        expected-output: |
          12S1102|Visual Programming|2|D
          10S1002|Procedural Programming|2|D
          12S22999|Wiro Sableng|2022|Information Systems
          12S1102|12S22999|None|0.00
          10S1002|12S22999|None|0.00
          12S1102|12S22999|A|8.00
          10S1002|12S22999|AB|7.00
        comparison-method: contains
        timeout: 1
        max-score: 40
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T07-45-00-45-01_RESULTS: "${{steps.t07-45-00-45-01.outputs.result}}"
        T07-45-01-45-01_RESULTS: "${{steps.t07-45-01-45-01.outputs.result}}"
        T07-45-02-45-01_RESULTS: "${{steps.t07-45-02-45-01.outputs.result}}"
        T07-45-03-45-01_RESULTS: "${{steps.t07-45-03-45-01.outputs.result}}"
      with:
        runners: t07-45-00-45-01,t07-45-01-45-01,t07-45-02-45-01,t07-45-03-45-01
