name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t10&#45;01&#45;01
      id: t10-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: |
          student-add#12S22001#Winfrey Nainggolan#2022#male
          student-add#12S22002#Jeremy Nainggolan#2022#male
          student-add#12S22009#Dolok Butarbutar#2022#male
          student-add#12S22010#Reinaldy Hutapea#2022#male
          student-print-all-detail
          student-add#12S22014#Kezia Hutagaol#2022#female
          student-add#12S22015#Angelina Nadeak#2022#female
          student-add#12S22024#Pimpin Loi#2022#male
          student-add#12S22025#Bronson Siallagan#2022#male
          student-add#12S22026#Ruben Sianipar#2022#male
          student-print-all
          student-add#12S22027#Ferry Panjaitan#2022#male
          student-print-all-detail
          ---
        expected-output: |
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22001|Winfrey Nainggolan|2022|male
          12S22002|Jeremy Nainggolan|2022|male
          12S22009|Dolok Butarbutar|2022|male
          12S22010|Reinaldy Hutapea|2022|male
          12S22014|Kezia Hutagaol|2022|female
          12S22015|Angelina Nadeak|2022|female
          12S22024|Pimpin Loi|2022|male
          12S22025|Bronson Siallagan|2022|male
          12S22026|Ruben Sianipar|2022|male
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22014|Kezia Hutagaol|2022|female|unassigned
          12S22015|Angelina Nadeak|2022|female|unassigned
          12S22024|Pimpin Loi|2022|male|unassigned
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;01&#45;02
      id: t10-45-01-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;01&#45;02
        setup-command: make compile
        command: make -s test_01
        input: |
          student-add#12S22001#Winfrey Nainggolan#2022#male
          student-add#12S22002#Jeremy Nainggolan#2022#male
          student-add#12S22009#Dolok Butarbutar#2022#male
          student-add#12S22010#Reinaldy Hutapea#2022#male
          student-add#12S22014#Kezia Hutagaol#2022#female
          student-add#12S22015#Angelina Nadeak#2022#female
          student-add#12S22024#Pimpin Loi#2022#male
          student-add#12S22025#Bronson Siallagan#2022#male
          student-add#12S22026#Ruben Sianipar#2022#male
          student-add#12S22027#Ferry Panjaitan#2022#male
          student-print-all
          dorm-add#Antiokia#20#male
          dorm-add#Mamre#20#male
          dorm-add#Silo#20#male
          dorm-add#Mahanaim#20#male
          dorm-add#Nazaret#20#male
          dorm-add#Pniel#20#female
          dorm-add#Kapernaum#20#male
          dorm-print-all
          student-print-all-detail
          dorm-print-all-detail
          ---
        expected-output: |
          12S22001|Winfrey Nainggolan|2022|male
          12S22002|Jeremy Nainggolan|2022|male
          12S22009|Dolok Butarbutar|2022|male
          12S22010|Reinaldy Hutapea|2022|male
          12S22014|Kezia Hutagaol|2022|female
          12S22015|Angelina Nadeak|2022|female
          12S22024|Pimpin Loi|2022|male
          12S22025|Bronson Siallagan|2022|male
          12S22026|Ruben Sianipar|2022|male
          12S22027|Ferry Panjaitan|2022|male
          Antiokia|20|male
          Mamre|20|male
          Silo|20|male
          Mahanaim|20|male
          Nazaret|20|male
          Pniel|20|female
          Kapernaum|20|male
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22014|Kezia Hutagaol|2022|female|unassigned
          12S22015|Angelina Nadeak|2022|female|unassigned
          12S22024|Pimpin Loi|2022|male|unassigned
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|20|male|0
          Mamre|20|male|0
          Silo|20|male|0
          Mahanaim|20|male|0
          Nazaret|20|male|0
          Pniel|20|female|0
          Kapernaum|20|male|0
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;02&#45;01
      id: t10-45-02-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;02&#45;01
        setup-command: make compile
        command: make -s test_02
        input: |
          student-add#12S22001#Winfrey Nainggolan#2022#male
          student-add#12S22002#Jeremy Nainggolan#2022#male
          student-add#12S22009#Dolok Butarbutar#2022#male
          student-add#12S22010#Reinaldy Hutapea#2022#male
          student-add#12S22014#Kezia Hutagaol#2022#female
          student-add#12S22015#Angelina Nadeak#2022#female
          student-add#12S22024#Pimpin Loi#2022#male
          student-add#12S22025#Bronson Siallagan#2022#male
          student-add#12S22026#Ruben Sianipar#2022#male
          student-add#12S22027#Ferry Panjaitan#2022#male
          dorm-add#Antiokia#5#male
          dorm-add#Mamre#5#male
          dorm-add#Silo#5#male
          dorm-add#Mahanaim#5#male
          dorm-add#Nazaret#5#male
          dorm-add#Pniel#5#female
          dorm-add#Kapernaum#5#male
          student-print-all-detail
          dorm-print-all-detail
          assign-student#12S22001#Antiokia
          assign-student#12S22002#Antiokia
          assign-student#12S22009#Antiokia
          assign-student#12S22010#Antiokia
          assign-student#12S22014#Pniel
          assign-student#12S22015#Pniel
          assign-student#12S22024#Antiokia
          assign-student#12S22025#Antiokia
          assign-student#12S22026#Antiokia
          assign-student#12S22027#Antiokia
          student-print-all-detail
          dorm-print-all-detail
          ---
        expected-output: |
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22014|Kezia Hutagaol|2022|female|unassigned
          12S22015|Angelina Nadeak|2022|female|unassigned
          12S22024|Pimpin Loi|2022|male|unassigned
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|5|male|0
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|0
          Nazaret|5|male|0
          Pniel|5|female|0
          Kapernaum|5|male|0
          12S22001|Winfrey Nainggolan|2022|male|Antiokia
          12S22002|Jeremy Nainggolan|2022|male|Antiokia
          12S22009|Dolok Butarbutar|2022|male|Antiokia
          12S22010|Reinaldy Hutapea|2022|male|Antiokia
          12S22014|Kezia Hutagaol|2022|female|Pniel
          12S22015|Angelina Nadeak|2022|female|Pniel
          12S22024|Pimpin Loi|2022|male|Antiokia
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|5|male|5
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|0
          Nazaret|5|male|0
          Pniel|5|female|2
          Kapernaum|5|male|0
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;03&#45;01
      id: t10-45-03-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;03&#45;01
        setup-command: make compile
        command: make -s test_03
        input: |
          student-add#12S22001#Winfrey Nainggolan#2022#male
          student-add#12S22002#Jeremy Nainggolan#2022#male
          student-add#12S22009#Dolok Butarbutar#2022#male
          student-add#12S22010#Reinaldy Hutapea#2022#male
          student-add#12S22014#Kezia Hutagaol#2022#female
          student-add#12S22015#Angelina Nadeak#2022#female
          student-add#12S22024#Pimpin Loi#2022#male
          student-add#12S22025#Bronson Siallagan#2022#male
          student-add#12S22026#Ruben Sianipar#2022#male
          student-add#12S22027#Ferry Panjaitan#2022#male
          dorm-add#Antiokia#5#male
          dorm-add#Mamre#5#male
          dorm-add#Silo#5#male
          dorm-add#Mahanaim#5#male
          dorm-add#Nazaret#5#male
          dorm-add#Pniel#5#female
          dorm-add#Kapernaum#5#female
          student-print-all-detail
          dorm-print-all-detail
          assign-student#12S22001#Antiokia
          assign-student#12S22002#Antiokia
          assign-student#12S22009#Antiokia
          assign-student#12S22010#Antiokia
          assign-student#12S22014#Pniel
          assign-student#12S22015#Pniel
          assign-student#12S22024#Antiokia
          assign-student#12S22025#Antiokia
          assign-student#12S22026#Antiokia
          assign-student#12S22027#Antiokia
          move-student#12S22001#Mahanaim
          move-student#12S22015#Nazaret
          move-student#12S22015#Kapernaum
          student-print-all-detail
          dorm-print-all-detail
          ---
        expected-output: |
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22014|Kezia Hutagaol|2022|female|unassigned
          12S22015|Angelina Nadeak|2022|female|unassigned
          12S22024|Pimpin Loi|2022|male|unassigned
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|5|male|0
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|0
          Nazaret|5|male|0
          Pniel|5|female|0
          Kapernaum|5|female|0
          12S22001|Winfrey Nainggolan|2022|male|Mahanaim
          12S22002|Jeremy Nainggolan|2022|male|Antiokia
          12S22009|Dolok Butarbutar|2022|male|Antiokia
          12S22010|Reinaldy Hutapea|2022|male|Antiokia
          12S22014|Kezia Hutagaol|2022|female|Pniel
          12S22015|Angelina Nadeak|2022|female|Kapernaum
          12S22024|Pimpin Loi|2022|male|Antiokia
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|5|male|4
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|1
          Nazaret|5|male|0
          Pniel|5|female|1
          Kapernaum|5|female|1
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t10&#45;03&#45;02
      id: t10-45-03-45-02
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;03&#45;02
        setup-command: make compile
        command: make -s test_03
        input: |
          student-add#12S22001#Winfrey Nainggolan#2022#male
          student-add#12S22002#Jeremy Nainggolan#2022#male
          student-add#12S22009#Dolok Butarbutar#2022#male
          student-add#12S22010#Reinaldy Hutapea#2022#male
          student-add#12S22014#Kezia Hutagaol#2022#female
          student-add#12S22015#Angelina Nadeak#2022#female
          student-add#12S22024#Pimpin Loi#2022#male
          student-add#12S22025#Bronson Siallagan#2022#male
          student-add#12S22026#Ruben Sianipar#2022#male
          student-add#12S22027#Ferry Panjaitan#2022#male
          dorm-add#Antiokia#5#male
          dorm-add#Mamre#5#male
          dorm-add#Silo#5#male
          dorm-add#Mahanaim#5#male
          dorm-add#Nazaret#5#male
          dorm-add#Pniel#5#female
          dorm-add#Kapernaum#5#female
          student-print-all-detail
          dorm-print-all-detail
          assign-student#12S22001#Antiokia
          assign-student#12S22002#Antiokia
          assign-student#12S22009#Antiokia
          assign-student#12S22010#Antiokia
          assign-student#12S22014#Pniel
          assign-student#12S22015#Pniel
          assign-student#12S22024#Antiokia
          assign-student#12S22025#Antiokia
          assign-student#12S22026#Antiokia
          assign-student#12S22027#Antiokia
          move-student#12S22025#Nazaret
          move-student#12S22026#Nazaret
          move-student#12S22027#Nazaret
          move-student#12S22001#Mahanaim
          move-student#12S22015#Nazaret
          move-student#12S22015#Kapernaum
          student-print-all-detail
          dorm-print-all-detail
          ---
        expected-output: |
          12S22001|Winfrey Nainggolan|2022|male|unassigned
          12S22002|Jeremy Nainggolan|2022|male|unassigned
          12S22009|Dolok Butarbutar|2022|male|unassigned
          12S22010|Reinaldy Hutapea|2022|male|unassigned
          12S22014|Kezia Hutagaol|2022|female|unassigned
          12S22015|Angelina Nadeak|2022|female|unassigned
          12S22024|Pimpin Loi|2022|male|unassigned
          12S22025|Bronson Siallagan|2022|male|unassigned
          12S22026|Ruben Sianipar|2022|male|unassigned
          12S22027|Ferry Panjaitan|2022|male|unassigned
          Antiokia|5|male|0
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|0
          Nazaret|5|male|0
          Pniel|5|female|0
          Kapernaum|5|female|0
          12S22001|Winfrey Nainggolan|2022|male|Mahanaim
          12S22002|Jeremy Nainggolan|2022|male|Antiokia
          12S22009|Dolok Butarbutar|2022|male|Antiokia
          12S22010|Reinaldy Hutapea|2022|male|Antiokia
          12S22014|Kezia Hutagaol|2022|female|Pniel
          12S22015|Angelina Nadeak|2022|female|Kapernaum
          12S22024|Pimpin Loi|2022|male|Antiokia
          12S22025|Bronson Siallagan|2022|male|Nazaret
          12S22026|Ruben Sianipar|2022|male|Nazaret
          12S22027|Ferry Panjaitan|2022|male|Nazaret
          Antiokia|5|male|4
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|1
          Nazaret|5|male|3
          Pniel|5|female|1
          Kapernaum|5|female|1
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T10-45-01-45-01_RESULTS: "${{steps.t10-45-01-45-01.outputs.result}}"
        T10-45-01-45-02_RESULTS: "${{steps.t10-45-01-45-02.outputs.result}}"
        T10-45-02-45-01_RESULTS: "${{steps.t10-45-02-45-01.outputs.result}}"
        T10-45-03-45-01_RESULTS: "${{steps.t10-45-03-45-01.outputs.result}}"
        T10-45-03-45-02_RESULTS: "${{steps.t10-45-03-45-02.outputs.result}}"
      with:
        runners: t10-45-01-45-01,t10-45-01-45-02,t10-45-02-45-01,t10-45-03-45-01,t10-45-03-45-02
